name: CI/CD Flask with Docker (Staged Rollout + Rollback)

on:
# push:
#   branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest   # works on managed runners too
    env:
      APP_NAME: raman-flask-app
      VERSION: ${{ github.run_number }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t $APP_NAME:$VERSION .

      - name: Deploy stage
        run: |
          docker rm -f ${APP_NAME} || true
          docker run -d --name ${APP_NAME} -p 5001:5000 $APP_NAME:$VERSION
          docker ps
          echo "✅ Staging running at http://localhost:5001/"

